### ISSUE TITLE
Fail to find dependency presto

### ISSUE THREAD

**Issue by schmattes42** [aet21/EpiSCORE#1]
Dear EpiScore Developers,

very interesting package!

Unfortunately, i fail installing it because, i am not able to find the dependency package "presto". Could you please guide me there?

P.S.: I am using R version 3.6.0

All the best,

Matthias

**Comment by aet21** [comment]
https://github.com/immunogenomics/presto

**Comment by schmattes42** [comment]
Thanks a lot! This solved it!

**Comment by YoannPa** [comment]
Would be nice to make this change: https://stackoverflow.com/a/32533483/6410117
