### ISSUE TITLE
Error in constAvBetaTSS function due to non-unique row names

### ISSUE THREAD

**Issue by Pigeongeon** [aet21/EpiSCORE#11]
I encountered an error while using the constAvBetaTSS() function from the EpiSCORE package in R. The function is supposed to collapse a DNA methylation data matrix at the gene promoter level. However, it throws an error stating that it is not allowed to have duplicate row names, despite the fact that the row names are confirmed to be unique.

Here is the code I used:

R
Copy code
merge_methy_450k_SXDYC_2 <- constAvBetaTSS(merge_methy_450k_SXDYC_2, type = "450k")
The error message I received is as follows:

sql
Copy code
Error in `.rowNamesDF<-`(x, value = value) : 
  Duplicate row names are not allowed.
  In addition: Warning message:
  Non-unique values when setting 'row.names': '100', '1000', '10001', '10002', '10003', ...
To troubleshoot the issue, I performed a check for duplicated row names before calling the function, and the check confirmed that all row names are unique:

R
Copy code
duplicated_rownames <- duplicated(rownames(merge_methy_450k_SXDYC_2))
if (any(duplicated_rownames)) {
  cat("There are", sum(duplicated_rownames), "duplicated row names.")
} else {
  cat("All row names are unique.")
}
Output:

sql
Copy code
All row names are unique.
I'm not sure why the constAvBetaTSS() function is throwing this error when there are no duplicate row names. I would appreciate any insights or suggestions for resolving this issue.

**Comment by Pigeongeon** [comment]
> # constAvBetaTSS() 函数将 DNAm 数据矩阵折叠到基因启动子水平
> merge_methy_450k_SXDYC_2 <- constAvBetaTSS(merge_methy_450k_SXDYC_2,type="450k")
Error in `.rowNamesDF<-`(x, value = value) : 不允许有重复的'row.names'
In addition: Warning message:
non-unique values when setting 'row.names': ‘100’, ‘1000’, ‘10001’, ‘10002’, ‘10003’, ‘100033413’, ‘100033414’, ‘100033416’, ‘100033420’, ‘100033423’, ‘100033424’, ‘100033427’, ‘100033430’, ‘100033434’, ‘100033435’, ‘100033436’, ‘100033437’, ‘100033443’, ‘100033444’, ‘100033447’, ‘100033450’, ‘100033451’, ‘100033454’, ‘100033811’, ‘100033812’, ‘100033813’, ‘100033814’, ‘100033818’, ‘10004’, ‘10006’, ‘10007’, ‘10008’, ‘1001’, ‘100113407’, ‘100124700’, ‘100126299’, ‘100126328’, ‘100126335’, ‘100126346’, ‘100126348’, ‘100126356’, ‘100128124’, ‘100128288’, ‘100128378’, ‘100128542’, ‘100128554’, ‘100128731’, ‘100128927’, ‘100129066’, ‘100129128’, ‘100129271’, ‘100129354’, ‘100129482’, ‘100129550’, ‘100129583’, ‘100129637’, ‘100129842’, ‘100130015’, ‘100130093 [... truncated] 
> # 检查 Merge_Methy_450k_SangerBox 数据矩阵的行名是否有重复
> duplicated_rownames <- duplicated(rownames(merge_methy_450k_SXDYC_2))
> if (any(duplicated_rownames)) {
+   cat("There are", sum(duplicated_rownames), "duplicated row names.")
+ } else {
+   cat("All row names are unique.")
+ }
All row names are unique.> any(duplicated(rownames(merge_methy_450k_SXDYC_2)))
[1] FALSE

**Comment by Pigeongeon** [comment]
When I run the package built-in data DummyBeta.m, the run is successful, and my own data merge_methy_450k_SXDYC_2 is in the same format as the package built-in data DummyBeta.m, with row name cgxxxxxxxx and column name sample id

> data(DummyBeta.m)
> DummyBeta.m <- constAvBetaTSS(DummyBeta.m,type="450k")
[1] "Done for regional gene group 1"
[1] "Done for regional gene group 2"
[1] "Done for regional gene group 3"
[1] "Done for regional gene group 4"
[1] "Done for regional gene group 5"
[1] "Done for regional gene group 6"

**Comment by aet21** [comment]
Most likely, your input data is a data frame, and not a matrix.......in R there is a difference between a matrix and data frame,
and in this instance, because all entries should be numerical, it makes more sense for it to be a matrix. You should read carefully
what the input objects to the R-function are.

**Comment by Pigeongeon** [comment]
> Most likely, your input data is a data frame, and not a matrix.......in R there is a difference between a matrix and data frame, and in this instance, because all entries should be numerical, it makes more sense for it to be a matrix. You should read carefully what the input objects to the R-function are.

Dear GitHub author, I want to express my heartfelt thanks to you! Your timely response is truly a lifesaver for me as an R language beginner. I wish you a happy life!😄😄😄😄😄😄😄😄😄😄
