### ISSUE TITLE
bulk RNA-seq prediction

### ISSUE THREAD

**Issue by zji90** [aet21/EpiSCORE#8]
Dear author,

Thanks for developing this tool. I was trying to use the tool to predict DNAm level for bulk RNA-seq data. Should I directly call ImputeDNAmRef(refexp.m=expr,...) where 'expr' is the log2 TPM values of bulk RNA-seq data? Or I need to do some further preprocessing?

**Comment by aet21** [comment]
Thanks for your question, but I get the impression you did not care to read the EpiSCORE papers. EpiSCORE is only designed to construct tissue-specific DNAm reference matrices, and it does so by imputation of scRNA-Seq data. To impute or predict DNAm levels for bulk-RNA-Seq data is a crazy idea which would be a terrible abuse of the EpiSCORE concept, so please do NOT do that!

**Comment by zji90** [comment]
Thanks for your reply. I did read the paper and software manual (but may not be in that much detail) and was trying to explore if EpiSCORE can be used for other purposes. If that's case I will not use EpiSCORE for predicting DNAm for bulk RNA-seq.

Thanks for your advise.
