### ISSUE TITLE
Duplicate gene names not allowed in constAvBetaTSS()

### ISSUE THREAD

**Issue by sarah-voisin** [aet21/EpiSCORE#9]
Hi Andrew,

I am trying to use constAvBetaTSS() on my beta-matrix, but I got the following error message:

Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique values when setting 'row.names': ‘100’, ‘1000’, ‘10000’, ‘10001’, ‘10002’, ‘100033413’, ‘100033414’, ‘100033416’, ‘100033420’, ‘100033427’, ‘100033430’, ‘100033435’, ‘100033436’, ‘100033437’, ‘100033447’, ‘100033450’, ‘100033454’, ‘100033813’, ‘100033814’, ‘100033818’, ‘10004’, ‘10006’, ‘10007’, ‘10008’, ‘1001’, ‘100113407’, ‘100124700’, ‘100126299’, ‘100126328’, ‘100126335’, ‘100126346’, ‘100126348’, ‘100126356’, ‘100127889’, ‘100128124’, ‘100128239’, ‘100128288’, ‘100128378’, ‘100128542’, ‘100128554’, ‘100128731’, ‘100128927’, ‘100129066’, ‘100129128’, ‘100129354’, ‘100129550’, ‘100129637’, ‘100129842’, ‘100130015’, ‘100130017’, ‘100130093’, ‘100130274’, ‘100130417’, ‘100130522’, ‘100130581’, ‘100130889’, ‘100130987’, ‘100131378’, ‘100131390’, ‘100131551’, ‘100132215’, ‘100132341’, ‘100132916’, ‘100133545’, ‘100133991’, ‘100134259’, ‘10014’, ‘100141515’, ‘100144604’, ‘10015’, ‘100151684’, ‘100169752’, ‘100170220’, ‘100170841’, ‘10018’, ‘100188949’, ‘100188953’, ‘100189589’ [... truncated]

It seems like the error is happening in the following line of code from the constAvBetaTSS() function:
rownames(tmp.m) <- probeInfo.lv$EID[group.idx]

For your information, I am using a 450K dataset that I preprocessed myself and whose head looks like this:
![image](https://github.com/aet21/EpiSCORE/assets/33650106/c39a36e0-23d8-406a-a0cb-51f3276d51d6)

Thank you for your help.

Kind regards,

Sarah Voisin

**Comment by aet21** [comment]
Sarah,
I am near 100% sure this error is caused by the input object not being a matrix, but something else e.g. a data frame. I just tested it and it reports exactly this type of error if you input the data as a date-frame, but if you read the function description it says the input should be a MATRIX. In R, you should pay attention to what we say the input should be.
Hope this helps,
A

**Comment by sarah-voisin** [comment]
Thank you, Andrew, it worked!
I shall pay close attention to the object format next time :)
